const Koa = require('koa');
const BodyParser = require('koa-bodyparser');
const Logger = require('koa-logger');
const cors = require('koa-cors');
const home = require('./routes/index');
const users = require('./routes/users');
const films = require('./routes/films');
const video = require('./routes/videos');
const filmsImg = require('./routes/filmImg');
const app = new Koa();

app.use(BodyParser());
app.use(Logger());
app.use(cors());
app.use(home.routes());
app.use(users.routes());
app.use(films.routes());
app.use(video.routes());
app.use(filmsImg.routes());
app.listen(3001);
